[package]
name = "pls"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.26", features = ["derive"] }
colored = "3.0.0"
dirs = "6.0.0"
duct = "0.13.7"
indicatif = "0.17.9"
reqwest = { version = "0.12.12", features = ["blocking", "json"] }
url = "2.5.4"
